name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make project.c
      run: make project.c
  deploy:
    runs-on: ubuntu-latest
    needs:
      - build

    steps:
      - name: Deploy executable file
        run: gcc project.c 
      - name: Run
        run: ./a.out
