name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: gcc project.c
    - name: make project.c
      run: make project.c
  deploy:
    runs-on: ubuntu-latest
    needs:
      - build

    steps:
      - name: Deploy executable file
        run: |
          ssh root@<your-server> cp tic-tac-toe /usr/local/bin
          ssh root@<your-server> chmod +x /usr/local/bin/tic-tac-toe
